### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jenkennedy** [RawBData/Checkoff#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- [x] Update MVP's to match our outlined mvps (reach out if you feel strongly about any of those)
    - Tasks
    - Lists
    - List summary (time, num tasks, num completed)
    - Search
    - Bonus: Autocomplete SmartAdd of task properties
    - Bonus: Subtasks

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- [x] Remove the bullet points below the tables for primary keys - don't need those.  Same with index bullet points. Only need the bullet points for foreign keys and unique
    - eg: `task_id` references `tasks` would be a bullet for the `taggings` table
- [x] `tag_id` in the `taggings` table should be integer instead of string
- [x] with the update of mvp list, we'll want a `lists` table along with `list_tasks` joins table

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- [x] need to update wildcard names for when there are two `id`'s.  eg( `DELETE /api/list/:id/tasks/:id` should be `DELETE /api/list/:list_id/tasks/:id`
- [x] need POST and DELETE routes for `taggings`

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by jenkennedy** [comment]
Looking good so far! I left some comments for the docs you've completed so far above.  Let me know if you have any questions!

**Comment by RawBData** [comment]
I have made the changes mentioned above.

**Comment by jenkennedy** [comment]
Awesome we are super close! Take a look at the remaining unchecked items and new comments and make any necessary changes.  Slack me if you have any questions!

**Comment by RawBData** [comment]
I have 
1- Added tagging routes to the backend
2- Snake cased the sample state
3-Changed one of the id's names when there are two wildcard id's in a backend route

**Comment by jenkennedy** [comment]
Awesome! Only one thing left and then you are good to go to start user auth! Let me know when you're done and I'll double check and close the issue. 
- [ ] Looks like there are still a few routes that need the wildcard variable names updated

**Comment by RawBData** [comment]
OK. I updated the wildcard routes again and added list front end routes too.

**Comment by jenkennedy** [comment]
Awesome job!
